name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64]

    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.20'

    - name: Build the binary
      run: |
        GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o bin/vlr-${{ matrix.goos }}-${{ matrix.goarch }}

    - name: Upload binary to release
      uses: actions/upload-artifact@v2
      with:
        name: bin/vlr-${{ matrix.goos }}-${{ matrix.goarch }}
        path: bin/vlr-${{ matrix.goos }}-${{ matrix.goarch }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download release binaries
      uses: actions/download-artifact@v2
      with:
        path: .

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          bin/vlr-linux-amd64
          bin/vlr-windows-amd64.exe
          bin/vlr-darwin-amd64
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
